In [99]:
import pandas as pd
import numpy as np

In [146]:
df=pd.read_csv("C:\\Users\\Phani\\Downloads\\Multinomial-Naive-Bayes-master\\Multinomial-Naive-Bayes-master\\first_batch.csv")

In [147]:
import pandas as pd
import numpy as np

from sklearn.naive_bayes import MultinomialNB

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score
import time

#library for regular expretion
import re

In [149]:
df['TITLE'].replace('', np.nan, inplace=True)

In [150]:
df=df[['TITLE','CATEGORY']]

In [151]:
df['TITLE'].isna().sum()

0

In [152]:
df.shape

(65, 2)

In [153]:
df['CATEGORY'].value_counts()

e    32
t    22
b    11
Name: CATEGORY, dtype: int64

In [154]:
import nltk
import string

In [155]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [156]:
txt=df['TITLE'][1]

In [157]:
l=[]
for i in txt:
    if i not in string.punctuation:
        l.append(i)
        

In [158]:
text=''.join(l)

In [159]:
text

'Feds Charles Plosser sees high bar for change in pace of tapering'

In [160]:
txt

"Fed's Charles Plosser sees high bar for change in pace of tapering"

In [161]:
def punctuncation_remove(n_txt):
    l=[]
    for i in n_txt:
        if i not in string.punctuation:
            l.append(i)
    return l

            

In [162]:
df['TITLE']=df['TITLE'].apply(punctuncation_remove)

In [163]:
df['CATEGORY'].value_counts()

e    32
t    22
b    11
Name: CATEGORY, dtype: int64

In [186]:
def joins(txts):
    return " ".join(txts)

In [165]:
df['TITLE']=df['TITLE'].apply(joins)

In [166]:
df

TITLE CATEGORY
0   Fed official says weak data caused by weather ...        b
1   Feds Charles Plosser sees high bar for change ...        b
2   US open Stocks fall after Fed official hints a...        b
3   Fed risks falling behind the curve Charles Plo...        b
4    Feds Plosser Nasty Weather Has Curbed Job Growth        b
..                                                ...      ...
60  GM recalls another 24M vehicles for belts bags...        t
61  Business update Parade of GM recalls rolls on ...        t
62                        GM keeps recalling vehicles        t
63                                    More GM recalls        t
64                    10 largest GM recalls this year        t

[65 rows x 2 columns]

In [167]:
from sklearn.feature_extraction.text import CountVectorizer

In [168]:
t=[df['TITLE'][0]]

In [169]:
vector=CountVectorizer()

In [170]:
vector.fit(t)

CountVectorizer()

In [171]:
vector.vocabulary_

{'fed': 3,
 'official': 5,
 'says': 6,
 'weak': 10,
 'data': 2,
 'caused': 1,
 'by': 0,
 'weather': 11,
 'should': 7,
 'not': 4,
 'slow': 8,
 'taper': 9}

In [172]:
t

['Fed official says weak data caused by weather should not slow taper']

In [173]:
vectors=vector.transform(t)

In [174]:
print(vectors)  ## (0--> 0th row, 0--> word encoded as 0) 1--> no of occurences of the word 

  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 6)	1
  (0, 7)	1
  (0, 8)	1
  (0, 9)	1
  (0, 10)	1
  (0, 11)	1


In [175]:
x=df['TITLE']

In [176]:
df['CATEGORY'].replace({'b':0,'e':1,'t':2},inplace=True)

In [177]:
df

TITLE  CATEGORY
0   Fed official says weak data caused by weather ...         0
1   Feds Charles Plosser sees high bar for change ...         0
2   US open Stocks fall after Fed official hints a...         0
3   Fed risks falling behind the curve Charles Plo...         0
4    Feds Plosser Nasty Weather Has Curbed Job Growth         0
..                                                ...       ...
60  GM recalls another 24M vehicles for belts bags...         2
61  Business update Parade of GM recalls rolls on ...         2
62                        GM keeps recalling vehicles         2
63                                    More GM recalls         2
64                    10 largest GM recalls this year         2

[65 rows x 2 columns]

In [178]:
from nltk.corpus import stopwords

In [200]:
import string
def text_cleaning(a):
 cleaning = [char for char in a if char not in string.punctuation]
 #print(cleaning)
 cleaning=''.join(cleaning)
 #print(cleaning)   
 return [word for word in cleaning.split() if word.lower() not in stopwords.words('english')]

In [180]:
def stopwordsrem(txt):
    x=[]
    for i in txt.split():
        if i not in stopwords.words("english"):
            x.append(i)
    return x

In [181]:
df['TITLE']=df['TITLE'].apply(stopwordsrem)

In [187]:
df

TITLE  CATEGORY
0   [Fed, official, says, weak, data, caused, weat...         0
1   [Feds, Charles, Plosser, sees, high, bar, chan...         0
2   [US, open, Stocks, fall, Fed, official, hints,...         0
3   [Fed, risks, falling, behind, curve, Charles, ...         0
4   [Feds, Plosser, Nasty, Weather, Has, Curbed, J...         0
..                                                ...       ...
60  [GM, recalls, another, 24M, vehicles, belts, b...         2
61  [Business, update, Parade, GM, recalls, rolls,...         2
62                   [GM, keeps, recalling, vehicles]         2
63                                [More, GM, recalls]         2
64                   [10, largest, GM, recalls, year]         2

[65 rows x 2 columns]

In [189]:
df['TITLE']=df['TITLE'].apply(joins)

In [190]:
df

TITLE  CATEGORY
0   Fed official says weak data caused weather slo...         0
1   Feds Charles Plosser sees high bar change pace...         0
2   US open Stocks fall Fed official hints acceler...         0
3   Fed risks falling behind curve Charles Plosser...         0
4    Feds Plosser Nasty Weather Has Curbed Job Growth         0
..                                                ...       ...
60         GM recalls another 24M vehicles belts bags         2
61  Business update Parade GM recalls rolls 24M ve...         2
62                        GM keeps recalling vehicles         2
63                                    More GM recalls         2
64                         10 largest GM recalls year         2

[65 rows x 2 columns]

In [262]:
b_transfrom=CountVectorizer(analyzer=text_cleaning).fit(df['TITLE'])

In [263]:
b_transfrom.vocabulary_

{'Fed': 61,
 'official': 202,
 'says': 221,
 'weak': 243,
 'data': 171,
 'caused': 167,
 'weather': 244,
 'slow': 224,
 'taper': 229,
 'Feds': 62,
 'Charles': 38,
 'Plosser': 109,
 'sees': 222,
 'high': 183,
 'bar': 160,
 'change': 168,
 'pace': 205,
 'tapering': 230,
 'US': 141,
 'open': 203,
 'Stocks': 131,
 'fall': 176,
 'hints': 184,
 'accelerated': 155,
 'risks': 219,
 'falling': 177,
 'behind': 162,
 'curve': 170,
 'Nasty': 96,
 'Weather': 147,
 'Curbed': 45,
 'Job': 81,
 'Growth': 73,
 'May': 86,
 'Accelerate': 18,
 'Tapering': 136,
 'Pace': 104,
 'Taper': 135,
 'may': 195,
 'expects': 175,
 'unemployment': 236,
 '62': 14,
 'end': 174,
 '2014': 4,
 'jobs': 190,
 'growth': 182,
 'last': 193,
 'month': 197,
 'hit': 185,
 'weatherFed': 245,
 'President': 113,
 'ECB': 54,
 'unlikely': 237,
 'sterilisation': 225,
 'SMP': 121,
 'purchases': 207,
 'traders': 235,
 'sterilization': 226,
 'Box': 32,
 'Office': 102,
 'XMen': 153,
 'Days': 50,
 'Future': 68,
 'Past': 106,
 'Nabs': 95,
 '26

In [264]:
t_bow=b_transfrom.transform(df['TITLE'])

In [265]:
print(t_bow)

  (0, 61)	1
  (0, 167)	1
  (0, 171)	1
  (0, 202)	1
  (0, 221)	1
  (0, 224)	1
  (0, 229)	1
  (0, 243)	1
  (0, 244)	1
  (1, 38)	1
  (1, 62)	1
  (1, 109)	1
  (1, 160)	1
  (1, 168)	1
  (1, 183)	1
  (1, 205)	1
  (1, 222)	1
  (1, 230)	1
  (2, 61)	1
  (2, 131)	1
  (2, 141)	1
  (2, 155)	1
  (2, 176)	1
  (2, 184)	1
  (2, 202)	1
  :	:
  (60, 69)	1
  (60, 158)	1
  (60, 159)	1
  (60, 163)	1
  (60, 213)	1
  (60, 240)	1
  (61, 7)	1
  (61, 36)	1
  (61, 69)	1
  (61, 105)	1
  (61, 213)	1
  (61, 220)	1
  (61, 238)	1
  (61, 240)	1
  (62, 69)	1
  (62, 191)	1
  (62, 212)	1
  (62, 240)	1
  (63, 69)	1
  (63, 213)	1
  (64, 2)	1
  (64, 69)	1
  (64, 192)	1
  (64, 213)	1
  (64, 249)	1


In [205]:
X=t_bow.toarray()

In [206]:
X.shape

(65, 256)

In [211]:
##tfidf- term frequency inverse document freaquency to know the most significantwords
from sklearn.feature_extraction.text import TfidfTransformer

In [212]:
tf=TfidfTransformer()

In [213]:
tf.fit(t_bow)

TfidfTransformer()

In [215]:
tfid_title=tf.transform(t_bow)

In [221]:
x=tfid_title.toarray()

In [222]:
y=df['CATEGORY']

In [225]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [261]:
x_train.shape

(52, 256)

In [227]:
x_test

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.53125073, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [228]:
y_train

37    1
15    1
59    2
48    2
28    1
3     0
51    2
46    2
64    2
45    2
52    2
9     0
10    0
58    2
63    2
20    1
49    2
40    1
13    1
33    1
8     0
25    1
38    1
23    1
41    1
2     0
44    2
31    1
12    1
36    1
4     0
34    1
7     0
39    1
6     0
43    2
22    1
17    1
14    1
5     0
54    2
56    2
32    1
61    2
26    1
53    2
27    1
21    1
1     0
24    1
50    2
11    1
Name: CATEGORY, dtype: int64

In [229]:
from sklearn.naive_bayes import BernoulliNB,MultinomialNB

In [230]:
cl2=MultinomialNB()

In [231]:
cl2.fit(x_train,y_train)

MultinomialNB()

In [233]:
y_pred=cl2.predict(x_test)

In [234]:
from sklearn.metrics import accuracy_score

In [235]:
accuracy_score(y_test,y_pred)

0.9230769230769231

In [239]:
inputs=['brodacasting fees for the array was very large'])

In [246]:
t=['Fed official says weak data caused by weather should not slow taper']

In [274]:
from sklearn.pipeline import make_pipeline
model=make_pipeline(b_transfrom, cl2)

In [247]:
vector=CountVectorizer()

In [267]:
d=b_transfrom.transform(t).toarray()

In [271]:
d.shape

(1, 256)

In [277]:
model.predict(inputs)

array([1], dtype=int64)

In [270]:
cl2.predict(d)

array([0], dtype=int64)